### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by vinnichase**

### CODE REVIEW

**Comment by vinnichase** [comment]
[Create CI for Microservices](https://trello.com/c/ktBRBfTt/1-create-ci-for-microservices)

**Comment by vinnichase** [comment]
[Set Up Fargate Infrastructure](https://trello.com/c/9QxTSViG/2-set-up-fargate-infrastructure)

**Review by NiklasMencke — APPROVED** [review]

**Comment by vinnichase** [comment]
[got-ui: Create CI for Frontend](https://trello.com/c/pTK4Illd/11-got-ui-create-ci-for-frontend)

**Comment by vinnichase** [comment]
[got-ui: Create CI for Frontend](https://trello.com/c/pTK4Illd/11-got-ui-create-ci-for-frontend)

**Pull request merged**
